// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oialkgtqednpfgtnerls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYWxrZ3RxZWRucGZndG5lcmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTE0NTcsImV4cCI6MjA3MDgyNzQ1N30.stnw84yILPxhFPXDawHAfmT2SS_SFndLlZepJQx_Mh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});